imagesNamespace: argoproj
controllerImage: workflow-controller
uiImage: argoui
imagesTag: latest
controllerName: workflow-controller
enableWebConsole: false
executorImage: argoexec
uiName: ui
crdVersion: v1alpha1
instanceID:
serviceAccount:

installMinio: true
minioBucketName: argo-artifacts
