version: 2.1
jobs:
  noop:
    docker:
      - image: bash
    steps:
      - run: echo "CircleCI is disabled on gh-pages branch"

workflows:
  version: 2
  gh-pages:
    jobs:
      - noop:
          filters:
            branches:
              ignore:
                - gh-pages
