imageNamespace: argoproj
ciImage: argoci
imageTag: latest

argo-ci:
  imagesNamespace: argoproj
  imagesTag: v2.0.0-alpha3
  enableWebConsole: false
  installMinio: true
  minioBucketName: argo-artifacts
